d = {}

name = input("enter friends name: ")
lang = input("fav language: ")
d.update({name: lang})
name = input("enter friends name: ")
lang = input("fav language: ")
d.update({name: lang})
name = input("enter friends name: ")
lang = input("fav language: ")
d.update({name: lang})
name = input("enter friends name: ")
lang = input("fav language: ")
d.update({name: lang})
print(d)