s = set()
n = int(input("enter a number: "))
s.add(n)
n = input("enter a number: ")
s.add(int(n))
n = input("enter a number: ")
s.add(int(n))
n = input("enter a number: ")
s.add(int(n))
n = input("enter a number: ")
s.add(int(n))
n = input("enter a number: ")
s.add(int(n))
n = input("enter a number: ")
s.add(int(n))
n = input("enter a number: ")
s.add(int(n))
print(s)